source 'http://rubygems.org'

gem 'rails', '3.1.1'

group :production do
  gem 'pg'
end
group :development, :test do
  gem 'sqlite3'
  gem 'capybara'
  gem 'haml-rails'
  gem 'hpricot'
  gem 'ruby_parser'
  gem 'web-app-theme', '~>0.8.0'
end

group :assets do
  gem 'sass-rails',   '~> 3.1.4'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
gem 'json'
gem 'nifty-generators'
gem 'nokogiri'
gem 'haml'
gem 'devise'
gem 'kaminari'
gem 'cancan'
